- name: copy prometheus configuration
  ansible.builtin.template:
    src: "{{item}}.yml"
    dest: /opt/prometheus/{{item}}.yml
  loop:
    - promotheus
    - alerts


- name: Restart Prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: restarted


#- name: check if prometheus is working or not
#  ansible.builtin.shell: sleep 10 ; netstat -lntp  | grep 9090


- name: Wait for Prometheus is started or not
  ansible.builtin.wait_for:
    port: 9090
    delay: 10
    timeout: 15
