

- name: configuring nodeJS repos
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

- name: Install nodejs
  ansible.builtin.yum:
    name: nodejs
    state: installed

- name: Include task list in play
  ansible.builtin.import_tasks:
    file: app_prereq.yml

- name: Install NodeJS dependencies
  ansible.builtin.shell: npm install
  args:
    chdir: /app

- name: Include schema setup
  ansible.builtin.import_tasks:
    file: schema_setup.yml

- name: Include SystemD
  ansible.builtin.import_tasks:
    file: systemd_setup.yml


